version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/

volumes:
  postgres: